/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/groupchat`; params?: Router.UnknownInputParams; } | { pathname: `/groupinfo`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sadmindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/DashboardTab`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/ReportsTab`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/UsersTab`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/[userID]`, params: Router.UnknownInputParams & { userID: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/groupchat`; params?: Router.UnknownOutputParams; } | { pathname: `/groupinfo`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sadmindashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/sadmin_tabs/DashboardTab`; params?: Router.UnknownOutputParams; } | { pathname: `/sadmin_tabs/ReportsTab`; params?: Router.UnknownOutputParams; } | { pathname: `/sadmin_tabs/UsersTab`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/[userID]`, params: Router.UnknownOutputParams & { userID: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/groupchat${`?${string}` | `#${string}` | ''}` | `/groupinfo${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/sadmindashboard${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/sadmin_tabs/DashboardTab${`?${string}` | `#${string}` | ''}` | `/sadmin_tabs/ReportsTab${`?${string}` | `#${string}` | ''}` | `/sadmin_tabs/UsersTab${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/groupchat`; params?: Router.UnknownInputParams; } | { pathname: `/groupinfo`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sadmindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/DashboardTab`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/ReportsTab`; params?: Router.UnknownInputParams; } | { pathname: `/sadmin_tabs/UsersTab`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/[userID]`, params: Router.UnknownInputParams & { userID: string | number; } };
    }
  }
}
